module.exports = {
  User: require('./User'),
  AdminAuditLog: require('./AdminAuditLog'),
  Booking: require('./Booking'),
  Driver: require('./Driver'),
  Locale: require('./Locale'),
  Translation: require('./Translation'),
  BlogPost: require('./BlogPost'),
  Service: require('./Service'),
  Car: require('./Car'),
  EmailTemplate: require('./EmailTemplate'),
  ContactSubmission: require('./ContactSubmission'),
  IntegrationSetting: require('./IntegrationSetting'),
  ...require('./RolePermission'),
};
